[package]
name = "prost-example"
version = "0.2.0"
authors = ["kingxsp <jin.hb.zh@outlook.com>"]

[dependencies]
bytes = "0.4"
env_logger = "*"

prost = "0.2"
prost-derive = "0.2"

actix = "0.5"
actix-web = "0.5"
actix-protobuf = { path="../../" }