[alias]
chk = "check --workspace --all-features --tests --examples --bins"
lint = "clippy --workspace --tests --examples --bins -- -Dclippy::todo"
ci-min = "hack check --workspace --no-default-features"
ci-check-min-tests = "hack check --workspace --no-default-features --tests --examples"
ci-check = "check --workspace --bins --tests --examples"
ci-test = "test --workspace --all-features --lib --tests --examples --bins --no-fail-fast"
ci-doctest = "hack test --workspace --all-features --doc --no-fail-fast"
